feat: install frontend and connect to docker compose

diff --git a/backend/Dockerfile b/backend/Dockerfile
--- a/backend/Dockerfile
+++ b/backend/Dockerfile
@@ -8,9 +8,16 @@ COPY . .
 
 ARG BUILD_ENV=dev
 
+RUN if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+    elif [ -f package-lock.json ]; then npm ci; \
+    elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i; \
+    else echo "Lockfile not found." && exit 1; \
+    fi
+
 RUN if [ "$BUILD_ENV" = "prod" ]; then npm run build -- -p tsconfig.build.json;\
     elif [ "$BUILD_ENV" = "preprod" ]; then npm run build -- -p tsconfig.build.json;\
-    else npm run build -- -p tsconfig.build.json; fi
+    else npm run build -- -p tsconfig.build.json; \
+    fi
 
 FROM node:22.3-alpine AS prod
 WORKDIR /app
